using System;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

//[assembly: Extension]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Scope = "member", Target = "Microsoft.Band.BandClient.#ParseSensorSubscriptionPayload(Microsoft.Band.BandClient+SensorSubscriptionQueueItem)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Band.BandClient.#SortTiles(System.Collections.Generic.IEnumerable`1<Microsoft.Band.Tiles.TileRepresentation>)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Band.BandClient.#SortTilesNoImages(System.Collections.Generic.IEnumerable`1<Microsoft.Band.Tiles.TileData>)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2219:DoNotRaiseExceptionsInExceptionClauses", Scope = "member", Target = "Microsoft.Band.BandClient.#RunUsingSynchronizedFirmwareUI(System.Action,System.Action)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Band.BandClient.#ValidateTileTheme(Microsoft.Band.BandTheme,System.Guid)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "id", Scope = "member", Target = "Microsoft.Band.BandClient.#ValidateTileTheme(Microsoft.Band.BandTheme,System.Guid)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "theme", Scope = "member", Target = "Microsoft.Band.BandClient.#ValidateTileTheme(Microsoft.Band.BandTheme,System.Guid)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "Microsoft.Band.BandColor")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "Microsoft.Band.BandException.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "Microsoft.Band.BandException.#.ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "Microsoft.Band.BandException.#.ctor(System.String,System.Exception)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "Microsoft.Band.BandIOException.#.ctor()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "Microsoft.Band.BandIOException.#.ctor(System.String)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "member", Target = "Microsoft.Band.BandIOException.#.ctor(System.String,System.Exception)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1032:ImplementStandardExceptionConstructors", Scope = "type", Target = "Microsoft.Band.BandOperationException")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Band.Sensors.BandSensorBase`1.#ProcessSensorReading(!0)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "bufferSize", Scope = "member", Target = "Microsoft.Band.Bgr565Pbgra32ConversionStream.#CopyTo(System.IO.Stream,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Microsoft.Band.PooledBuffer.#.ctor(Microsoft.Band.BufferPool,System.Byte[],System.Int32)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2208:InstantiateArgumentExceptionsCorrectly", Scope = "member", Target = "Microsoft.Band.PooledBuffer.#Length")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "length", Scope = "member", Target = "Microsoft.Band.PooledBuffer.#Undispose(System.Int32)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "zero", Scope = "member", Target = "Microsoft.Band.BufferPool.#GetBuffer(System.Boolean)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "byteCount", Scope = "member", Target = "Microsoft.Band.CargoCommandWriter.#WriteString(System.String)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "stream", Scope = "member", Target = "Microsoft.Band.CargoStreamReader.#CopyTo(System.IO.Stream,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "stream", Scope = "member", Target = "Microsoft.Band.CargoStreamWriter.#CopyFromStream(System.IO.Stream,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "Microsoft.Band.DateTimeOffsetExtensions.#ToFileTimeStruct(System.DateTimeOffset)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1813:AvoidUnsealedAttributes", Scope = "type", Target = "Microsoft.Band.ExcludeFromTestCodeCoverageAttribute")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Band.IBandClientManager.#GetBandsAsync()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Band.Sensors.IBandContactSensor.#GetCurrentStateAsync()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Band.Notifications.IBandNotificationManager.#SendMessageAsync(System.Guid,System.String,System.String,System.DateTimeOffset,Microsoft.Band.Notifications.MessageFlags)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1024:UsePropertiesWhereAppropriate", Scope = "member", Target = "Microsoft.Band.Sensors.IBandSensor`1.#GetCurrentUserConsent()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Band.Tiles.IBandTileManager.#GetTilesAsync()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1006:DoNotNestGenericTypesInMemberSignatures", Scope = "member", Target = "Microsoft.Band.Tiles.IBandTileManager.#GetTilesAsync(System.Threading.CancellationToken)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "Microsoft.Band.ByteArrayProxyStream.#SetBuffer(System.Byte[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "length", Scope = "member", Target = "Microsoft.Band.ByteArrayProxyStream.#SetBuffer(System.Byte[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "buffer", Scope = "member", Target = "Microsoft.Band.ByteArrayProxyStream.#SetBuffer(System.Byte[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "Microsoft.Band.ByteArrayProxyStream.#Read(System.Byte[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "offset", Scope = "member", Target = "Microsoft.Band.ByteArrayProxyStream.#Write(System.Byte[],System.Int32,System.Int32)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "Microsoft.Band.Tiles.Pages.Margins")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "structure", Scope = "member", Target = "Microsoft.Band.MarshalUtils.#GetByteCount`1(!!0&)")]
[assembly: SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "structure", Scope = "member", Target = "Microsoft.Band.MarshalUtils.#GetByteCount`1(!!0)")]
[assembly: SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "color", Scope = "member", Target = "Microsoft.Band.Tiles.Pages.PageElement.#DeserializeFromBand(Microsoft.Band.ICargoReader)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1026:DefaultParametersShouldNotBeUsed", Scope = "member", Target = "Microsoft.Band.Tiles.Pages.PageLayout.#.ctor(Microsoft.Band.Tiles.Pages.PagePanel)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1804:RemoveUnusedLocals", MessageId = "deepChildCount", Scope = "member", Target = "Microsoft.Band.Tiles.Pages.PageLayout.#DeserializeFromBand(Microsoft.Band.ICargoReader)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1815:OverrideEqualsAndOperatorEqualsOnValueTypes", Scope = "type", Target = "Microsoft.Band.Tiles.Pages.PageRect")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1822:MarkMembersAsStatic", Scope = "member", Target = "Microsoft.Band.BandClient.#ColateTileDataAndIconLists(System.Collections.Generic.List`1<Microsoft.Band.Tiles.TileData>,System.Collections.Generic.List`1<Microsoft.Band.PooledBuffer>)")]
[assembly: AssemblyTitle("Microsoft.Band")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyTrademark("")]
[assembly: NeutralResourcesLanguage("en")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly: InternalsVisibleTo("Microsoft.Band.Desktop")]
[assembly: InternalsVisibleTo("Microsoft.Band.Store")]
[assembly: InternalsVisibleTo("Microsoft.Band.Store_UAP")]
[assembly: InternalsVisibleTo("Microsoft.Band.Phone")]
[assembly: InternalsVisibleTo("Microsoft.Band.Phone_UAP")]
[assembly: InternalsVisibleTo("Microsoft.Band.Windows")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Desktop")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Store")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Phone")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Windows")]
[assembly: InternalsVisibleTo("Microsoft.Health.App.Background")]
[assembly: InternalsVisibleTo("Microsoft.Health.App.Platform.WindowsPhone")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Phone.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.E2E.Admin.Phone.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Desktop.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Desktop.Manual.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Admin.Phone.Manual.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Phone.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Windows.Test")]
[assembly: InternalsVisibleTo("Microsoft.Band.Desktop.Test")]
[assembly: InternalsVisibleTo("Microsoft.Health.App.Core.UnitTest")]
[assembly: AssemblyFileVersion("1.3.20517.1")]
[assembly: AssemblyVersion("1.3.20517.1")]
